### ISSUE TITLE
Bus support?

### ISSUE THREAD

**Issue by honigc** [codeforboston/mbta-ninja#63]
Should be easy enough to add in the usual manner. Possible issue type (relevant this winter) would be "stop inaccessible" because it hasn't been shoveled out.

http://mbta.com/winter/bus_status/

**Comment by JacobEvelyn** [comment]
@honigc do you have thoughts on how to fit this into the UI?

**Comment by honigc** [comment]
Because there are so many bus lines, maybe we could collapse them all under
a "buses" section, and start by including only the key lines listed by the
MBTA? Buses also have issue types that trains don't, and tend to have many
more stops on a route, so more thought needs to go into the per-line UI as
well.

**Comment by davidlago** [comment]
@honigc @JacobEvelyn Added bus support on PR #109. I've separated the events by type, so that we can have specific events for buses. Added silver lines. Also, if we start adding buses, we might have to rethink the interface since it is getting pretty crowded already after adding all of the commuter rail lines.
